=== Acasasec/LM/dadoXMLcrearDTD_Amaia_Casas/equipos_de_futbol.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT equipos_de_futbol (equipo+)>
<!ELEMENT equipo (nombre, ciudad, entrenador, jugadores)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT ciudad (#PCDATA)>
  <!ELEMENT entrenador (#PCDATA)>
  <!ELEMENT jugadores (jugador+)>

<!ELEMENT jugador (nombre1, nacionalidad)>
  <!ELEMENT nombre1 (#PCDATA)>
  <!ELEMENT nacionalidad (#PCDATA)>

<!ATTLIST jugador
          posicion CDATA #REQUIRED>

=== Acasasec/LM/dadoXMLcrearDTD_Amaia_Casas/equipos_de_futbol.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos_de_futbol SYSTEM "equipos_de_futbol.dtd">
<equipos_de_futbol>
   <equipo>
      <nombre>Levante</nombre>
      <ciudad>Valencia</ciudad>
      <entrenador> </entrenador>
      <jugadores>
         <jugador posicion="portero">
            <nombre1>Javier Jiménez</nombre1>
            <nacionalidad>española</nacionalidad>
         </jugador>
         <jugador posicion="delantero">
            <nombre1>Nong</nombre1>
            <nacionalidad>camerunés</nacionalidad>
         </jugador>
      </jugadores>
   </equipo>
   <equipo>
      <nombre>Real Sociedad</nombre>
      <ciudad>San Sebastián</ciudad>
      <entrenador></entrenador>
      <jugadores>
         <jugador posicion="portero">
            <nombre1>Claudio Bravo</nombre1>
            <nacionalidad>chilena</nacionalidad>
         </jugador>
         <jugador posicion="defensa">
            <nombre1>Mikel González</nombre1>
            <nacionalidad>española</nacionalidad>
         </jugador>
      </jugadores>
   </equipo>
</equipos_de_futbol>
