<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE factura [
  <!ELEMENT factura (datos_emisor, datos_cliente, datos_detalle)>
      
  <!ELEMENT datos_emisor (nombre, CIF, telefono)>
  <!ELEMENT datos_cliente (nombre, CIF, telefono)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT CIF (#PCDATA)>
  <!ELEMENT telefono (#PCDATA)>
  <!ELEMENT datos_detalle (linea+)>
  <!ELEMENT linea (descripcion, cantidad, oferta?, PVP)>
  <!ELEMENT descripcion (#PCDATA)>
  <!ELEMENT cantidad (#PCDATA)>
  <!ELEMENT oferta EMPTY>
  <!ELEMENT PVP (#PCDATA)>

<!ATTLIST factura 
        numero CDATA #REQUIRED
        fecha CDATA #REQUIRED>
        
<!ATTLIST datos_detalle importe CDATA #REQUIRED>        
<!ATTLIST linea 
        codigo_articulo ID #REQUIRED
        tipo (Libro|DVD|Varios) #IMPLIED>

]>

<factura  numero="27"  fecha="18/12/2013">
    <datos_emisor>
        <nombre>Libreria Pérez</nombre>
        <CIF>44555666B</CIF>
        <telefono>777888999</telefono>    
    </datos_emisor>    
    
    <datos_cliente>
        <nombre>Biblioteca Txantrea</nombre>
        <CIF>33111222A</CIF>
        <telefono>333999444</telefono>
    </datos_cliente>
    
    <datos_detalle importe="85€">
      <linea codigo_articulo="AW7" tipo="Libro">
          <descripcion>Analitica Web 2.0</descripcion>
          <cantidad>1</cantidad>
          <oferta />
          <PVP>25€</PVP>      
      </linea>
      <linea codigo_articulo="CP5" tipo="DVD">
         <descripcion>Curso de HTML</descripcion>
         <cantidad>2</cantidad>
         <oferta />
         <PVP>30€</PVP>
      </linea>    
    </datos_detalle>
</factura>