<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE panel_de_vuelos [
  <!ELEMENT panel_de_vuelos (nombre, vuelos, fecha_panel)>
  <!ELEMENT nombre (#PCDATA)>
  <!ELEMENT vuelos (vuelo+)>
  <!ELEMENT vuelo (diario?, origen, destino, hora_salida, hora_llegada)>
  <!ELEMENT diario EMPTY>
  <!ELEMENT origen (#PCDATA)>
  <!ELEMENT destino (#PCDATA)>
  <!ELEMENT hora_salida (#PCDATA)>
  <!ELEMENT hora_llegada (#PCDATA)>
  <!ELEMENT fecha_panel (#PCDATA)>  
      <!ATTLIST vuelo codigo ID #REQUIRED>
      <!ATTLIST vuelo estado (C|E|R) "E">
  ]>
  
  <panel_de_vuelos>
    <nombre>JFK</nombre>
    <vuelos>
      <vuelo codigo="V22"  estado="R">
        <diario />
        <origen>New York</origen>
        <destino>Chicago</destino>
        <hora_salida>9:30</hora_salida>
        <hora_llegada>11:30</hora_llegada>      
      </vuelo>
      
      <vuelo codigo="V23" estado="C">
        <diario />
        <origen>New York</origen>
        <destino>Miami</destino>
        <hora_salida>10:15</hora_salida>
        <hora_llegada>11:15</hora_llegada>
      </vuelo>    
    </vuelos>
  
    <fecha_panel>20/12/2013</fecha_panel>
  </panel_de_vuelos>